name: however-demo
recipe: pantheon
config:
  framework: drupal8
  site: however-demo
  id: 78d5fc9a-da95-4e48-911f-51edc37d0838
  xdebug: true
  config:
    php: .lando.php.ini
services:
  appserver:
    xdebug: true
