features:
  node_user_picture: 0
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 0
  path: 'public://HH2DAP_logo_2_w_parens-cropped.png'
favicon:
  use_default: 1
